# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 10
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.0005
  weight_decay: !!float 1e-5
# Data config
data:
  task: enh_single
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
  segment: 2.0
  train_clean_dir: ''
  train_noisy_dir: ''
  test_clean_dir: ''
  test_noisy_dir: ''
