data:
  mode: min
  nondefault_nsrc: null
  sample_rate: 8000
  segment: 2
  task: enh_single
  clean_files: "/root/clean/**/*.wav"
  ir_files: "/root/irs/**/*.wav"
filterbank:
  kernel_size: 16
  n_filters: 64
  stride: 8
masknet:
  bidirectional: true
  bn_chan: 128
  chunk_size: 100
  dropout: 0
  hid_size: 128
  hop_size: 50
  in_chan: 64
  mask_act: sigmoid
  n_repeats: 6
  out_chan: 64
optim:
  lr: 0.0005
  optimizer: adam
  weight_decay: 1.0e-05
training:
  batch_size: 20
  early_stop: true
  epochs: 200
  gradient_clipping: 5
  half_lr: true
  num_workers: 4
