# Training config
training:
  epochs: 200
  #batch_size: 16
  batch_size: 20
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  json_dir: data/
  val_prop: 0.2
  #segment: 3.11
  segment: 3
