# Training config
training:
  epochs: 200
  #batch_size: 16
  #batch_size: 25 # 8 GB
  batch_size: 40 # 24 GB
  num_workers: 15
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  lr: 0.0005
  weight_decay: !!float 1e-5
# Data config
data:
  real_rirs_dir: "/root/pred-rirs-2020-10-22-small-rooms-16khz"
  dns_rirs_dir: "/root/impulse_responses-16khz"
  dns_clean_dir: "/root/DNS-Challenge-clean-nonsilent"
  dns_noise_dir: "/root/noise-16khz"
  #segment: 3.11
  segment: 3
