# Model config
# Best model:
model:
  out_channels: 512
  in_channels: 512
  num_blocks: 34
  upsampling_depth: 5
  enc_kernel_size: 21
  enc_num_basis: 512
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.0005
# Data config
data:
  task: enh_single
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
  segment: 2.0
  train_clean_dir: ''
  train_noisy_dir: ''
  test_clean_dir: ''
  test_noisy_dir: ''
