# Model config
# SuDoRM-RF 1.0x:
model:
  out_channels: 128
  in_channels: 512
  num_blocks: 16
  upsampling_depth: 4
  enc_kernel_size: 21
  enc_num_basis: 512
  num_sources: 1
# Best model:
#model:
  #out_channels: 512
  #in_channels: 512 (?)
  #num_blocks: 34
  #upsampling_depth: 4
  #enc_kernel_size: 21
  #enc_num_basis: 512 (?)
  #num_sources: 1
# Default improved
#model:
  #out_channels: 256
  #in_channels: 512
  #num_blocks: 16
  #upsampling_depth: 5
  #enc_kernel_size: 21
  #enc_num_basis: 512
  #num_sources: 1
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_clean
  sample_rate: 8000
  mode: min
  segment: 3.0
